-- ACTIVIDAD 2 SCRIPT PARA CREACION DE DATABASE AIRBNB
-- CREADO POR:  ALEJANDRO MIRANDA SANCHEZ
-- CODIGO:      230182001
-- FECHA:       22/08/2023


---- BORRADO INICIAL ----

ALTER TABLE AIRBNB_REVIEW
DROP CONSTRAINT REV_USER_ID_FK;
ALTER TABLE AIRBNB_REVIEW
DROP CONSTRAINT REV_PLACE_ID_FK;

ALTER TABLE AIRBNB_PLACE
DROP CONSTRAINT PLA_USER_ID_FK;
ALTER TABLE AIRBNB_PLACE
DROP CONSTRAINT PLA_CITY_ID_FK;

ALTER TABLE AIRBNB_CITY
DROP CONSTRAINT CIT_STATE_ID_FK;

ALTER TABLE AIRBNB_PLACE_AMENITY
DROP CONSTRAINT PL_AM_AMENITY_ID_FK;
ALTER TABLE AIRBNB_PLACE_AMENITY
DROP CONSTRAINT PL_AM_PLACE_ID_FK;

DROP TABLE AIRBNB_REVIEW;
DROP TABLE AIRBNB_USER;
DROP TABLE AIRBNB_PLACE;
DROP TABLE AIRBNB_AMENITY;
DROP TABLE AIRBNB_PLACE_AMENITY;
DROP TABLE AIRBNB_STATE;
DROP TABLE AIRBNB_CITY;


---- CREATE TABLES ----

CREATE TABLE AIRBNB_REVIEW (
    ID VARCHAR(10) NOT NULL,
    UPDATED_AT DATE NOT NULL,
    CREATED_AT DATE NOT NULL,
    USER_ID VARCHAR(10),
    PLACE_ID VARCHAR(10),
    TEXT VARCHAR(80) NOT NULL
);

CREATE TABLE AIRBNB_USER(
    ID VARCHAR(10) NOT NULL,
    UPDATED_AT DATE,
    CREATED_AT DATE,
    EMAIL VARCHAR(20),
    PASSWORD VARCHAR(20),
    FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(20)
);

CREATE TABLE AIRBNB_PLACE (
    ID VARCHAR(10) NOT NULL,
    UPDATED_AT DATE,
    CREATED_AT DATE,
    USER_ID VARCHAR(10),
    NAME VARCHAR(20),
    CITY_ID VARCHAR(30),
    DESCRIPTION VARCHAR(100),
    NUMBER_ROOMS INT DEFAULT 0,
    NUMBER_BATHROOMS INT DEFAULT 0,
    MAX_GUEST INT DEFAULT 0,
    PRICE_BY_NIGHT INT DEFAULT 0,
    LATITUDE FLOAT,
    LONGITUDE FLOAT
);

CREATE TABLE AIRBNB_AMENITY (
    ID VARCHAR(10) NOT NULL,
    UPDATED_AT DATE,
    CREATED_AT DATE,
    NAME VARCHAR(20)
);

CREATE TABLE AIRBNB_PLACE_AMENITY (
    AMENITY_ID VARCHAR(10) NOT NULL,
    PLACE_ID VARCHAR(20) NOT NULL
);

CREATE TABLE AIRBNB_STATE (
    ID VARCHAR(10) NOT NULL,
    UPDATED_AT DATE,
    CREATED_AT DATE,
    NAME VARCHAR(20)
);

CREATE TABLE AIRBNB_CITY (
    ID VARCHAR(10) NOT NULL,
    UPDATED_AT DATE,
    CREATED_AT DATE,
    STATE_ID VARCHAR(10),
    NAME VARCHAR(20)
);

---- CREATE PRIMARY KEYS ----

ALTER TABLE AIRBNB_REVIEW
MODIFY ID PRIMARY KEY;

ALTER TABLE AIRBNB_USER
MODIFY ID PRIMARY KEY;

ALTER TABLE AIRBNB_PLACE
MODIFY ID PRIMARY KEY;

ALTER TABLE AIRBNB_AMENITY
MODIFY ID PRIMARY KEY;

ALTER TABLE AIRBNB_STATE
MODIFY ID PRIMARY KEY;

ALTER TABLE AIRBNB_CITY
MODIFY ID PRIMARY KEY;

---- CREATE CONSTRAIN ----

---- REVIEW ----

ALTER TABLE AIRBNB_REVIEW
ADD CONSTRAINT REV_USER_ID_FK
    FOREIGN KEY (USER_ID)
    REFERENCES AIRBNB_USER(ID);

ALTER TABLE AIRBNB_REVIEW
ADD CONSTRAINT REV_PLACE_ID_FK
    FOREIGN KEY (PLACE_ID)
    REFERENCES AIRBNB_PLACE(ID);

---- PLACE ----

ALTER TABLE AIRBNB_PLACE
ADD CONSTRAINT PLA_USER_ID_FK
    FOREIGN KEY (USER_ID)
    REFERENCES AIRBNB_USER(ID);

ALTER TABLE AIRBNB_PLACE
ADD CONSTRAINT PLA_CITY_ID_FK
    FOREIGN KEY (CITY_ID)
    REFERENCES AIRBNB_CITY(ID);

---- CITY ----

ALTER TABLE AIRBNB_CITY
ADD CONSTRAINT CIT_STATE_ID_FK
    FOREIGN KEY (STATE_ID)
    REFERENCES AIRBNB_STATE(ID);
    
---- PLACE-AMENITY ----

ALTER TABLE AIRBNB_PLACE_AMENITY
ADD CONSTRAINT PL_AM_AMENITY_ID_FK
    FOREIGN KEY (AMENITY_ID)
    REFERENCES AIRBNB_AMENITY(ID);
    
ALTER TABLE AIRBNB_PLACE_AMENITY
ADD CONSTRAINT PL_AM_PLACE_ID_FK
    FOREIGN KEY (PLACE_ID)
    REFERENCES AIRBNB_PLACE(ID);
    